### ISSUE TITLE
Crash during save replay.

### ISSUE THREAD

**Issue by xdudi** [xmoto/xmoto#143]
```
Thread 1 "xmoto" received signal SIGSEGV, Segmentation fault.
0x0000555555604fc5 in UIMsgBox::paint (this=0x555557e24f20) at /usr/src/github/xmoto/src/gui/basic/GUI.cpp:413
413         FontGlyph *fg = fm->getGlyph(s);
(gdb) bt
#0  0x0000555555604fc5 in UIMsgBox::paint() (this=0x555557e24f20) at /usr/src/github/xmoto/src/gui/basic/GUI.cpp:413
#1  0x00005555556090aa in UIRoot::_RootPaint(int, int, UIWindow*, UIRect*) (this=0x555558a0d1e0, x=0, y=0, pWindow=0x555557e24f20, pRect=0x7fffffffdb10) at /usr/src/github/xmoto/src/gui/basic/GUI.cpp:1193
#2  0x0000555555609234 in UIRoot::paint() (this=0x555558a0d1e0) at /usr/src/github/xmoto/src/gui/basic/GUI.cpp:1225
#3  0x00005555556b4f2c in StateMenu::render() (this=0x555557db7790) at /usr/src/github/xmoto/src/states/StateMenu.cpp:77
#4  0x00005555556ae015 in StateManager::render() (this=0x555555ff3b40) at /usr/src/github/xmoto/src/states/StateManager.cpp:599
#5  0x00005555557429ec in GameApp::run_loop() (this=0x5555559f68a0) at /usr/src/github/xmoto/src/xmoto/GameInit.cpp:959
#6  0x000055555573e4d1 in GameApp::run(int, char**) (this=0x5555559f68a0, nNumArgs=1, ppcArgs=0x7fffffffde78) at /usr/src/github/xmoto/src/xmoto/GameInit.cpp:162
#7  0x000055555573e2a8 in main(int, char**) (nNumArgs=1, ppcArgs=0x7fffffffde78) at /usr/src/github/xmoto/src/xmoto/GameInit.cpp:120
(gdb) p fm
$1 = (FontManager *) 0x0
(gdb)
```

It happened on the master branch.

**Comment by Nikekson** [comment]
Fixed by 2f232907d0e2f46b641399cebf95d38126c84c05
